lang: pt-BR
timezone: America/Sao_Paulo
theme: jekyll-theme-chirpy
title: Huncoding
tagline: Crie, Code e Compartilhe
description: O blog oficial do canal Huncoding. Conteúdo sobre programação, tecnologia e projetos.
url: "https://huncoding.github.io"
social:
  name: Otavio Celestino dos Santos
  email: ${{ secrets.BLOG_EMAIL }}
  links:
    - https://github.com/HunCoding
theme_mode: dark
avatar: "/assets/huncoding_logo.svg"
analytics:
  google:
    id: ${{ secrets.GOOGLE_ANALYTICS_ID }}
comments:
  provider: giscus
  giscus:
    repo: HunCoding/huncoding.github.io
    repo_id: ${{ secrets.GISCUS_REPO_ID }}
    category: Ideas
    category_id: ${{ secrets.GISCUS_CATEGORY_ID }}
highlighter_theme: github-dark-high-contrast
paginate: 10
paginate_path: /page:num/
permalink: /:title/
github:
  username: HunCoding

plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true
      permalink: /:title/
      toc: true
      breadcrumb:
        - label: Posts
          url: /
      sidebar:
        nav: posts

  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: true
      breadcrumb:
        - label: Home
          url: /
      sidebar:
        nav: posts

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      comments: true
      breadcrumb:
        - label: Home
          url: /
      sidebar:
        nav: posts

# Ensure .nojekyll is included in the build
include:
  - .nojekyll

# Open Graph and Social Media
og_image: "/assets/img/og-image.png"
twitter_image: "/assets/img/og-image.png"

# Social Media Meta Tags
twitter:
  username: huncoding
  card: summary_large_image

# Open Graph defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      og_image: "/assets/img/og-image.png"
      twitter_image: "/assets/img/og-image.png"

# Jekyll SEO Tag configuration
seo:
  type: "WebSite"
  name: "Huncoding"
  description: "O blog oficial do canal Huncoding. Conteúdo sobre programação, tecnologia e projetos."
  image: "/assets/img/og-image.png"
  twitter:
    card: "summary_large_image"
    site: "@huncoding"
